/* tslint:disable */
/* eslint-disable */
/**
 * Checkouts
 * Create checkouts from existing carts using BigCommerce checkout logic.
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CouponCodeRequest
 */
export interface CouponCodeRequest {
    /**
     * 
     * @type {string}
     * @memberof CouponCodeRequest
     */
    couponCode?: string;
}

export function CouponCodeRequestFromJSON(json: any): CouponCodeRequest {
    return CouponCodeRequestFromJSONTyped(json, false);
}

export function CouponCodeRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CouponCodeRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'couponCode': !exists(json, 'coupon_code') ? undefined : json['coupon_code'],
    };
}

export function CouponCodeRequestToJSON(value?: CouponCodeRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'coupon_code': value.couponCode,
    };
}


