/* tslint:disable */
/* eslint-disable */
/**
 * Checkouts
 * Create checkouts from existing carts using BigCommerce checkout logic.
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LineItemCustomItems
 */
export interface LineItemCustomItems {
    /**
     * 
     * @type {number}
     * @memberof LineItemCustomItems
     */
    quantity: number;
    /**
     * 
     * @type {string}
     * @memberof LineItemCustomItems
     */
    id?: string;
    /**
     * 
     * @type {number}
     * @memberof LineItemCustomItems
     */
    extendedListPrice?: number;
    /**
     * 
     * @type {number}
     * @memberof LineItemCustomItems
     */
    listPrice?: number;
    /**
     * 
     * @type {string}
     * @memberof LineItemCustomItems
     */
    sku?: string;
    /**
     * 
     * @type {string}
     * @memberof LineItemCustomItems
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof LineItemCustomItems
     */
    imageUrl?: string;
}

export function LineItemCustomItemsFromJSON(json: any): LineItemCustomItems {
    return LineItemCustomItemsFromJSONTyped(json, false);
}

export function LineItemCustomItemsFromJSONTyped(json: any, ignoreDiscriminator: boolean): LineItemCustomItems {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'quantity': json['quantity'],
        'id': !exists(json, 'id') ? undefined : json['id'],
        'extendedListPrice': !exists(json, 'extended_list_price') ? undefined : json['extended_list_price'],
        'listPrice': !exists(json, 'list_price') ? undefined : json['list_price'],
        'sku': !exists(json, 'sku') ? undefined : json['sku'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'imageUrl': !exists(json, 'image_url') ? undefined : json['image_url'],
    };
}

export function LineItemCustomItemsToJSON(value?: LineItemCustomItems | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'quantity': value.quantity,
        'id': value.id,
        'extended_list_price': value.extendedListPrice,
        'list_price': value.listPrice,
        'sku': value.sku,
        'name': value.name,
        'image_url': value.imageUrl,
    };
}


