/* tslint:disable */
/* eslint-disable */
/**
 * Storefront Carts
 * Manage cart operations and data via front-end JavaScript on BigCommerce stencil powered storefronts.
 *
 * The version of the OpenAPI document: Storefront
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    LineItemsRequestOneOf,
    LineItemsRequestOneOf1,
    LineItemsRequestOneOf2,
    LineItemsRequestOneOfFromJSONTyped,
    LineItemsRequestOneOfToJSON,
    LineItemsRequestOneOf1FromJSONTyped,
    LineItemsRequestOneOf1ToJSON,
    LineItemsRequestOneOf2FromJSONTyped,
    LineItemsRequestOneOf2ToJSON,
} from './';

/**
 * @type LineItemsRequest
 * Cart object used in add items requests.
 * @export
 */
export type LineItemsRequest = LineItemsRequestOneOf | LineItemsRequestOneOf1 | LineItemsRequestOneOf2;

export function LineItemsRequestFromJSON(json: any): LineItemsRequest {
    return LineItemsRequestFromJSONTyped(json, false);
}

export function LineItemsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): LineItemsRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return { ...LineItemsRequestOneOfFromJSONTyped(json, true), ...LineItemsRequestOneOf1FromJSONTyped(json, true), ...LineItemsRequestOneOf2FromJSONTyped(json, true) };
}

export function LineItemsRequestToJSON(value?: LineItemsRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return { ...LineItemsRequestOneOfToJSON(value), ...LineItemsRequestOneOf1ToJSON(value), ...LineItemsRequestOneOf2ToJSON(value) };
}

