/* tslint:disable */
/* eslint-disable */
/**
 * Storefront Carts
 * Manage cart operations and data via front-end JavaScript on BigCommerce stencil powered storefronts.
 *
 * The version of the OpenAPI document: Storefront
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    RequestLineItemGiftCertificate,
    RequestLineItemGiftCertificateFromJSON,
    RequestLineItemGiftCertificateFromJSONTyped,
    RequestLineItemGiftCertificateToJSON,
} from './';

/**
 * 
 * @export
 * @interface RequestCartOneOf1
 */
export interface RequestCartOneOf1 {
    /**
     * 
     * @type {Array<RequestLineItemGiftCertificate>}
     * @memberof RequestCartOneOf1
     */
    giftCertificates: Array<RequestLineItemGiftCertificate>;
    /**
     * 
     * @type {string}
     * @memberof RequestCartOneOf1
     */
    locale?: string;
}

export function RequestCartOneOf1FromJSON(json: any): RequestCartOneOf1 {
    return RequestCartOneOf1FromJSONTyped(json, false);
}

export function RequestCartOneOf1FromJSONTyped(json: any, ignoreDiscriminator: boolean): RequestCartOneOf1 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'giftCertificates': ((json['giftCertificates'] as Array<any>).map(RequestLineItemGiftCertificateFromJSON)),
        'locale': !exists(json, 'locale') ? undefined : json['locale'],
    };
}

export function RequestCartOneOf1ToJSON(value?: RequestCartOneOf1 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'giftCertificates': ((value.giftCertificates as Array<any>).map(RequestLineItemGiftCertificateToJSON)),
        'locale': value.locale,
    };
}


