/* tslint:disable */
/* eslint-disable */
/**
 * Storefront Carts
 * Manage cart operations and data via front-end JavaScript on BigCommerce stencil powered storefronts.
 *
 * The version of the OpenAPI document: Storefront
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RequestLineItemGiftCertificateRecipient
 */
export interface RequestLineItemGiftCertificateRecipient {
    /**
     * Contact's email address.
     * @type {string}
     * @memberof RequestLineItemGiftCertificateRecipient
     */
    email?: string;
    /**
     * Contact's name.
     * @type {string}
     * @memberof RequestLineItemGiftCertificateRecipient
     */
    name?: string;
}

export function RequestLineItemGiftCertificateRecipientFromJSON(json: any): RequestLineItemGiftCertificateRecipient {
    return RequestLineItemGiftCertificateRecipientFromJSONTyped(json, false);
}

export function RequestLineItemGiftCertificateRecipientFromJSONTyped(json: any, ignoreDiscriminator: boolean): RequestLineItemGiftCertificateRecipient {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'email': !exists(json, 'email') ? undefined : json['email'],
        'name': !exists(json, 'name') ? undefined : json['name'],
    };
}

export function RequestLineItemGiftCertificateRecipientToJSON(value?: RequestLineItemGiftCertificateRecipient | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'email': value.email,
        'name': value.name,
    };
}


