/* tslint:disable */
/* eslint-disable */
/**
 * Storefront Carts
 * Manage cart operations and data via front-end JavaScript on BigCommerce stencil powered storefronts.
 *
 * The version of the OpenAPI document: Storefront
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * This will always be the same between cart and checkout.
 * @export
 * @interface ResponseCartCurrency
 */
export interface ResponseCartCurrency {
    /**
     * ISO-4217 currency code. (See: http://en.wikipedia.org/wiki/ISO_4217.)
     * @type {string}
     * @memberof ResponseCartCurrency
     */
    code?: string;
}

export function ResponseCartCurrencyFromJSON(json: any): ResponseCartCurrency {
    return ResponseCartCurrencyFromJSONTyped(json, false);
}

export function ResponseCartCurrencyFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseCartCurrency {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'code': !exists(json, 'code') ? undefined : json['code'],
    };
}

export function ResponseCartCurrencyToJSON(value?: ResponseCartCurrency | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'code': value.code,
    };
}


