/* tslint:disable */
/* eslint-disable */
/**
 * Customers V3
 * Create and manage customers.  - [Authentication](#authentication) - [Resources](#resources)  ## Authentication  Requests can be authenticated by sending an `access_token` via `X-Auth-Token` HTTP header:  ```http GET /stores/{$$.env.store_hash}/v3/customers host: api.bigcommerce.com Accept: application/json X-Auth-Token: {access_token} ```  |Header|Parameter|Description| |-|-|-| |`X-Auth-Token`|`access_token `|Obtained by creating an API account or installing an app in a BigCommerce control panel.|  ### OAuth Scopes  | UI Name                                      | Permission | Parameter                                     | |----------------------------------------------|------------|-----------------------------------------------| | Customers                                    | modify     | `store_v2_customers`                          | | Customers                                    | read-only  | `store_v2_customers_read_only`                | | Stored Payment Instruments                   | modify     | `store_stored_payment_instruments`            | | Stored Payment Instruments                   | read-only  | `store_stored_payment_instruments_read_only`  |  For more information on Authenticating BigCommerce APIs, see: [Authentication](https://developer.bigcommerce.com/api-docs/getting-started/authentication).  ## Resources * [Customer and Subscribers Overview](/api-docs/customers/customers-subscribers-overview).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Address1,
    Address1FromJSON,
    Address1FromJSONTyped,
    Address1ToJSON,
} from './';

/**
 * Response payload for the BigCommerce API.
 * @export
 * @interface AddressCollectionResponse1
 */
export interface AddressCollectionResponse1 {
    /**
     * 
     * @type {Array<Address1>}
     * @memberof AddressCollectionResponse1
     */
    data?: Array<Address1>;
    /**
     * 
     * @type {object}
     * @memberof AddressCollectionResponse1
     */
    meta?: object;
}

export function AddressCollectionResponse1FromJSON(json: any): AddressCollectionResponse1 {
    return AddressCollectionResponse1FromJSONTyped(json, false);
}

export function AddressCollectionResponse1FromJSONTyped(json: any, ignoreDiscriminator: boolean): AddressCollectionResponse1 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': !exists(json, 'data') ? undefined : ((json['data'] as Array<any>).map(Address1FromJSON)),
        'meta': !exists(json, 'meta') ? undefined : json['meta'],
    };
}

export function AddressCollectionResponse1ToJSON(value?: AddressCollectionResponse1 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': value.data === undefined ? undefined : ((value.data as Array<any>).map(Address1ToJSON)),
        'meta': value.meta,
    };
}


