/* tslint:disable */
/* eslint-disable */
/**
 * Customers V3
 * Create and manage customers.  - [Authentication](#authentication) - [Resources](#resources)  ## Authentication  Requests can be authenticated by sending an `access_token` via `X-Auth-Token` HTTP header:  ```http GET /stores/{$$.env.store_hash}/v3/customers host: api.bigcommerce.com Accept: application/json X-Auth-Token: {access_token} ```  |Header|Parameter|Description| |-|-|-| |`X-Auth-Token`|`access_token `|Obtained by creating an API account or installing an app in a BigCommerce control panel.|  ### OAuth Scopes  | UI Name                                      | Permission | Parameter                                     | |----------------------------------------------|------------|-----------------------------------------------| | Customers                                    | modify     | `store_v2_customers`                          | | Customers                                    | read-only  | `store_v2_customers_read_only`                | | Stored Payment Instruments                   | modify     | `store_stored_payment_instruments`            | | Stored Payment Instruments                   | read-only  | `store_stored_payment_instruments_read_only`  |  For more information on Authenticating BigCommerce APIs, see: [Authentication](https://developer.bigcommerce.com/api-docs/getting-started/authentication).  ## Resources * [Customer and Subscribers Overview](/api-docs/customers/customers-subscribers-overview).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BillingAddress
 */
export interface BillingAddress {
    /**
     * First name of the card holder
     * @type {string}
     * @memberof BillingAddress
     */
    firstName?: string;
    /**
     * Last name of the card holder
     * @type {string}
     * @memberof BillingAddress
     */
    lastName?: string;
    /**
     * 
     * @type {string}
     * @memberof BillingAddress
     */
    email?: string;
    /**
     * Company of the card holder
     * @type {string}
     * @memberof BillingAddress
     */
    company?: string;
    /**
     * 
     * @type {string}
     * @memberof BillingAddress
     */
    address1?: string;
    /**
     * 
     * @type {string}
     * @memberof BillingAddress
     */
    address2?: string;
    /**
     * 
     * @type {string}
     * @memberof BillingAddress
     */
    city?: string;
    /**
     * 
     * @type {string}
     * @memberof BillingAddress
     */
    postalCode?: string;
    /**
     * Represents state or province
     * @type {string}
     * @memberof BillingAddress
     */
    stateOrProvince?: string;
    /**
     * 
     * @type {string}
     * @memberof BillingAddress
     */
    stateOrProvinceCode?: string;
    /**
     * ISO-3166-1 2 letter country code
     * @type {string}
     * @memberof BillingAddress
     */
    countryCode?: string;
    /**
     * 
     * @type {string}
     * @memberof BillingAddress
     */
    phone?: string;
}

export function BillingAddressFromJSON(json: any): BillingAddress {
    return BillingAddressFromJSONTyped(json, false);
}

export function BillingAddressFromJSONTyped(json: any, ignoreDiscriminator: boolean): BillingAddress {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'firstName': !exists(json, 'first_name') ? undefined : json['first_name'],
        'lastName': !exists(json, 'last_name') ? undefined : json['last_name'],
        'email': !exists(json, 'email') ? undefined : json['email'],
        'company': !exists(json, 'company') ? undefined : json['company'],
        'address1': !exists(json, 'address1') ? undefined : json['address1'],
        'address2': !exists(json, 'address2') ? undefined : json['address2'],
        'city': !exists(json, 'city') ? undefined : json['city'],
        'postalCode': !exists(json, 'postal_code') ? undefined : json['postal_code'],
        'stateOrProvince': !exists(json, 'state_or_province') ? undefined : json['state_or_province'],
        'stateOrProvinceCode': !exists(json, 'state_or_province_code') ? undefined : json['state_or_province_code'],
        'countryCode': !exists(json, 'country_code') ? undefined : json['country_code'],
        'phone': !exists(json, 'phone') ? undefined : json['phone'],
    };
}

export function BillingAddressToJSON(value?: BillingAddress | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'first_name': value.firstName,
        'last_name': value.lastName,
        'email': value.email,
        'company': value.company,
        'address1': value.address1,
        'address2': value.address2,
        'city': value.city,
        'postal_code': value.postalCode,
        'state_or_province': value.stateOrProvince,
        'state_or_province_code': value.stateOrProvinceCode,
        'country_code': value.countryCode,
        'phone': value.phone,
    };
}


