/* tslint:disable */
/* eslint-disable */
/**
 * Carts
 * Create a cart using BigCommerce cart logic.
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Example as part of a Cart response:
 * 
 * ```
 * "discounts": [
 * 		{
 * 				"id": 2,
 * 				"discounted_amount": 2
 * 		},
 * 		{
 * 				"id": "coupon",
 * 				"discounted_amount": 0.42
 * 		}
 * ]
 * ```
 * @export
 * @interface AppliedDiscount1
 */
export interface AppliedDiscount1 {
    /**
     * The discounted amount.
     * @type {number}
     * @memberof AppliedDiscount1
     */
    discountedAmount?: number;
}

export function AppliedDiscount1FromJSON(json: any): AppliedDiscount1 {
    return AppliedDiscount1FromJSONTyped(json, false);
}

export function AppliedDiscount1FromJSONTyped(json: any, ignoreDiscriminator: boolean): AppliedDiscount1 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'discountedAmount': !exists(json, 'discounted_amount') ? undefined : json['discounted_amount'],
    };
}

export function AppliedDiscount1ToJSON(value?: AppliedDiscount1 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'discounted_amount': value.discountedAmount,
    };
}


