/* tslint:disable */
/* eslint-disable */
/**
 * Redirects
 * Manage 301 redirects for one or more storefronts powered by a single BigCommerce back-end.  **On This Page** - [Authentication](#authentication) - [OAuth Scopes](#oauth-scopes) ---   ## Authentication  Requests can be authenticated by sending an `access_token` via `X-Auth-Token` HTTP header:  ```http GET /stores/{$$.env.store_hash}/v3/catalog/summary host: api.bigcommerce.com Accept: application/json X-Auth-Token: {access_token} ```  |Header|Parameter|Description| |-|-|-| |`X-Auth-Token`|`access_token `|Obtained by creating an API account or installing an app in a BigCommerce control panel.|  For more information on Authenticating BigCommerce APIs, see: [Authentication](https://developer.bigcommerce.com/api-docs/getting-started/authentication).
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    MetaPaginationObjectPaginationLinks,
    MetaPaginationObjectPaginationLinksFromJSON,
    MetaPaginationObjectPaginationLinksFromJSONTyped,
    MetaPaginationObjectPaginationLinksToJSON,
} from './';

/**
 * 
 * @export
 * @interface MetaPaginationObjectPagination
 */
export interface MetaPaginationObjectPagination {
    /**
     * 
     * @type {number}
     * @memberof MetaPaginationObjectPagination
     */
    total?: number;
    /**
     * 
     * @type {number}
     * @memberof MetaPaginationObjectPagination
     */
    count?: number;
    /**
     * 
     * @type {number}
     * @memberof MetaPaginationObjectPagination
     */
    perPage?: number;
    /**
     * 
     * @type {number}
     * @memberof MetaPaginationObjectPagination
     */
    currentPage?: number;
    /**
     * 
     * @type {number}
     * @memberof MetaPaginationObjectPagination
     */
    totalPages?: number;
    /**
     * 
     * @type {MetaPaginationObjectPaginationLinks}
     * @memberof MetaPaginationObjectPagination
     */
    links?: MetaPaginationObjectPaginationLinks;
}

export function MetaPaginationObjectPaginationFromJSON(json: any): MetaPaginationObjectPagination {
    return MetaPaginationObjectPaginationFromJSONTyped(json, false);
}

export function MetaPaginationObjectPaginationFromJSONTyped(json: any, ignoreDiscriminator: boolean): MetaPaginationObjectPagination {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'total': !exists(json, 'total') ? undefined : json['total'],
        'count': !exists(json, 'count') ? undefined : json['count'],
        'perPage': !exists(json, 'per_page') ? undefined : json['per_page'],
        'currentPage': !exists(json, 'current_page') ? undefined : json['current_page'],
        'totalPages': !exists(json, 'total_pages') ? undefined : json['total_pages'],
        'links': !exists(json, 'links') ? undefined : MetaPaginationObjectPaginationLinksFromJSON(json['links']),
    };
}

export function MetaPaginationObjectPaginationToJSON(value?: MetaPaginationObjectPagination | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'total': value.total,
        'count': value.count,
        'per_page': value.perPage,
        'current_page': value.currentPage,
        'total_pages': value.totalPages,
        'links': MetaPaginationObjectPaginationLinksToJSON(value.links),
    };
}


