/* tslint:disable */
/* eslint-disable */
/**
 * Webhooks v3
 * Get notified when specific events occur on a BigCommerce store. For more information, see [Webhooks Overview](https://developer.bigcommerce.com/api-docs/store-management/webhooks/overview).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InlineResponse422Errors
 */
export interface InlineResponse422Errors {
    /**
     * 
     * @type {string}
     * @memberof InlineResponse422Errors
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse422Errors
     */
    primaryContactDistrict?: string;
}

export function InlineResponse422ErrorsFromJSON(json: any): InlineResponse422Errors {
    return InlineResponse422ErrorsFromJSONTyped(json, false);
}

export function InlineResponse422ErrorsFromJSONTyped(json: any, ignoreDiscriminator: boolean): InlineResponse422Errors {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'primaryContactDistrict': !exists(json, 'primary_contact.district') ? undefined : json['primary_contact.district'],
    };
}

export function InlineResponse422ErrorsToJSON(value?: InlineResponse422Errors | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'primary_contact.district': value.primaryContactDistrict,
    };
}


