/* tslint:disable */
/* eslint-disable */
/**
 * Webhooks v3
 * Get notified when specific events occur on a BigCommerce store. For more information, see [Webhooks Overview](https://developer.bigcommerce.com/api-docs/store-management/webhooks/overview).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    PaginationLinks,
    PaginationLinksFromJSON,
    PaginationLinksFromJSONTyped,
    PaginationLinksToJSON,
} from './';

/**
 * Data about the response, including pagination and collection totals.
 * @export
 * @interface Pagination
 */
export interface Pagination {
    /**
     * Total number of returned items across all pages.
     * @type {number}
     * @memberof Pagination
     */
    total?: number;
    /**
     * Number of items on current page.
     * @type {number}
     * @memberof Pagination
     */
    count?: number;
    /**
     * Maximum number of items per page.
     * @type {number}
     * @memberof Pagination
     */
    perPage?: number;
    /**
     * Current page number.
     * @type {number}
     * @memberof Pagination
     */
    currentPage?: number;
    /**
     * Total number of pages.
     * @type {number}
     * @memberof Pagination
     */
    totalPages?: number;
    /**
     * 
     * @type {PaginationLinks}
     * @memberof Pagination
     */
    links?: PaginationLinks;
}

export function PaginationFromJSON(json: any): Pagination {
    return PaginationFromJSONTyped(json, false);
}

export function PaginationFromJSONTyped(json: any, ignoreDiscriminator: boolean): Pagination {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'total': !exists(json, 'total') ? undefined : json['total'],
        'count': !exists(json, 'count') ? undefined : json['count'],
        'perPage': !exists(json, 'per_page') ? undefined : json['per_page'],
        'currentPage': !exists(json, 'current_page') ? undefined : json['current_page'],
        'totalPages': !exists(json, 'total_pages') ? undefined : json['total_pages'],
        'links': !exists(json, 'links') ? undefined : PaginationLinksFromJSON(json['links']),
    };
}

export function PaginationToJSON(value?: Pagination | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'total': value.total,
        'count': value.count,
        'per_page': value.perPage,
        'current_page': value.currentPage,
        'total_pages': value.totalPages,
        'links': PaginationLinksToJSON(value.links),
    };
}


