/* tslint:disable */
/* eslint-disable */
/**
 * Webhooks v3
 * Get notified when specific events occur on a BigCommerce store. For more information, see [Webhooks Overview](https://developer.bigcommerce.com/api-docs/store-management/webhooks/overview).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    StoreOrderMessageCreatedAllOfDataMessage,
    StoreOrderMessageCreatedAllOfDataMessageFromJSON,
    StoreOrderMessageCreatedAllOfDataMessageFromJSONTyped,
    StoreOrderMessageCreatedAllOfDataMessageToJSON,
} from './';

/**
 * A lightweight description of the event that triggered the webhook. Will vary depending on the event registered.
 * @export
 * @interface StoreOrderMessageCreatedAllOfData
 */
export interface StoreOrderMessageCreatedAllOfData {
    /**
     * will always be `order`
     * @type {string}
     * @memberof StoreOrderMessageCreatedAllOfData
     */
    type?: string;
    /**
     * ID of the order
     * @type {number}
     * @memberof StoreOrderMessageCreatedAllOfData
     */
    id?: number;
    /**
     * 
     * @type {StoreOrderMessageCreatedAllOfDataMessage}
     * @memberof StoreOrderMessageCreatedAllOfData
     */
    message?: StoreOrderMessageCreatedAllOfDataMessage;
}

export function StoreOrderMessageCreatedAllOfDataFromJSON(json: any): StoreOrderMessageCreatedAllOfData {
    return StoreOrderMessageCreatedAllOfDataFromJSONTyped(json, false);
}

export function StoreOrderMessageCreatedAllOfDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): StoreOrderMessageCreatedAllOfData {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': !exists(json, 'type') ? undefined : json['type'],
        'id': !exists(json, 'id') ? undefined : json['id'],
        'message': !exists(json, 'message') ? undefined : StoreOrderMessageCreatedAllOfDataMessageFromJSON(json['message']),
    };
}

export function StoreOrderMessageCreatedAllOfDataToJSON(value?: StoreOrderMessageCreatedAllOfData | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': value.type,
        'id': value.id,
        'message': StoreOrderMessageCreatedAllOfDataMessageToJSON(value.message),
    };
}


