/* tslint:disable */
/* eslint-disable */
/**
 * Webhooks v3
 * Get notified when specific events occur on a BigCommerce store. For more information, see [Webhooks Overview](https://developer.bigcommerce.com/api-docs/store-management/webhooks/overview).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * A lightweight description of the event that triggered the webhook. Will vary depending on the event registered.
 * @export
 * @interface StoreCartCouponAppliedAllOfData
 */
export interface StoreCartCouponAppliedAllOfData {
    /**
     * can be `cart` or `cart_line_item`
     * @type {string}
     * @memberof StoreCartCouponAppliedAllOfData
     */
    type?: string;
    /**
     * ID of the cart
     * @type {string}
     * @memberof StoreCartCouponAppliedAllOfData
     */
    id?: string;
    /**
     * ID of the coupon
     * @type {number}
     * @memberof StoreCartCouponAppliedAllOfData
     */
    couponId?: number;
}

export function StoreCartCouponAppliedAllOfDataFromJSON(json: any): StoreCartCouponAppliedAllOfData {
    return StoreCartCouponAppliedAllOfDataFromJSONTyped(json, false);
}

export function StoreCartCouponAppliedAllOfDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): StoreCartCouponAppliedAllOfData {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': !exists(json, 'type') ? undefined : json['type'],
        'id': !exists(json, 'id') ? undefined : json['id'],
        'couponId': !exists(json, 'couponId') ? undefined : json['couponId'],
    };
}

export function StoreCartCouponAppliedAllOfDataToJSON(value?: StoreCartCouponAppliedAllOfData | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': value.type,
        'id': value.id,
        'couponId': value.couponId,
    };
}


