/* tslint:disable */
/* eslint-disable */
/**
 * Webhooks v3
 * Get notified when specific events occur on a BigCommerce store. For more information, see [Webhooks Overview](https://developer.bigcommerce.com/api-docs/store-management/webhooks/overview).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    StoreCartAbandonedAllOf,
    StoreCartAbandonedAllOfFromJSON,
    StoreCartAbandonedAllOfFromJSONTyped,
    StoreCartAbandonedAllOfToJSON,
    StoreCartAbandonedAllOfData,
    StoreCartAbandonedAllOfDataFromJSON,
    StoreCartAbandonedAllOfDataFromJSONTyped,
    StoreCartAbandonedAllOfDataToJSON,
    WebhookCallbackBase,
    WebhookCallbackBaseFromJSON,
    WebhookCallbackBaseFromJSONTyped,
    WebhookCallbackBaseToJSON,
} from './';

/**
 * This webhook will fire once after a cart is abandoned. A cart is considered abandoned if no changes have been made for at least one hour after the last modified property. This hook is available for all store plans, regardless of whether the Abandoned Cart Saver feature is enabled.
 * 
 * ### Example callback:
 * 
 * ```json
 * {
 *   "created_at": 1561482670,
 *   "store_id": "1025646",
 *   "producer": "stores/{store_hash}",
 *   "scope": "store/cart/abandoned",
 *   "hash": "352e4afc6dd3fc85ea26bfdf3f91852604d57528",
 *   "data": {
 *     "type": "cart",
 *     "id": "09346904-4175-44fd-be53-f7e598531b6c"
 *   }
 * }
 * ```
 * 
 * ### Callback schema:
 * @export
 * @interface StoreCartAbandoned
 */
export interface StoreCartAbandoned {
    /**
     * Hook creation date as a Unix timestamp.
     * @type {number}
     * @memberof StoreCartAbandoned
     */
    readonly createdAt?: number;
    /**
     * A numerical identifier that is unique to each store.
     * @type {string}
     * @memberof StoreCartAbandoned
     */
    storeId?: string;
    /**
     * Will always follow the pattern `stores/store_hash`. This is the store that created the webhook.
     * @type {string}
     * @memberof StoreCartAbandoned
     */
    producer?: string;
    /**
     * The event registered when the webhook was created.
     * @type {string}
     * @memberof StoreCartAbandoned
     */
    scope?: string;
    /**
     * The payload data JSON encoded then passed through SH1 encryption.
     * @type {string}
     * @memberof StoreCartAbandoned
     */
    hash?: string;
    /**
     * 
     * @type {StoreCartAbandonedAllOfData}
     * @memberof StoreCartAbandoned
     */
    data?: StoreCartAbandonedAllOfData;
}

export function StoreCartAbandonedFromJSON(json: any): StoreCartAbandoned {
    return StoreCartAbandonedFromJSONTyped(json, false);
}

export function StoreCartAbandonedFromJSONTyped(json: any, ignoreDiscriminator: boolean): StoreCartAbandoned {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'createdAt': !exists(json, 'created_at') ? undefined : json['created_at'],
        'storeId': !exists(json, 'store_id') ? undefined : json['store_id'],
        'producer': !exists(json, 'producer') ? undefined : json['producer'],
        'scope': !exists(json, 'scope') ? undefined : json['scope'],
        'hash': !exists(json, 'hash') ? undefined : json['hash'],
        'data': !exists(json, 'data') ? undefined : StoreCartAbandonedAllOfDataFromJSON(json['data']),
    };
}

export function StoreCartAbandonedToJSON(value?: StoreCartAbandoned | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'store_id': value.storeId,
        'producer': value.producer,
        'scope': value.scope,
        'hash': value.hash,
        'data': StoreCartAbandonedAllOfDataToJSON(value.data),
    };
}


