/* tslint:disable */
/* eslint-disable */
/**
 * Webhooks v3
 * Get notified when specific events occur on a BigCommerce store. For more information, see [Webhooks Overview](https://developer.bigcommerce.com/api-docs/store-management/webhooks/overview).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    StoreOrderRefundCreatedAllOfData,
    StoreOrderRefundCreatedAllOfDataFromJSON,
    StoreOrderRefundCreatedAllOfDataFromJSONTyped,
    StoreOrderRefundCreatedAllOfDataToJSON,
} from './';

/**
 * A lightweight description of the event that triggered the webhook. Will vary depending on the event registered.
 * @export
 * @interface StoreOrderRefundCreatedAllOf
 */
export interface StoreOrderRefundCreatedAllOf {
    /**
     * 
     * @type {StoreOrderRefundCreatedAllOfData}
     * @memberof StoreOrderRefundCreatedAllOf
     */
    data?: StoreOrderRefundCreatedAllOfData;
}

export function StoreOrderRefundCreatedAllOfFromJSON(json: any): StoreOrderRefundCreatedAllOf {
    return StoreOrderRefundCreatedAllOfFromJSONTyped(json, false);
}

export function StoreOrderRefundCreatedAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): StoreOrderRefundCreatedAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': !exists(json, 'data') ? undefined : StoreOrderRefundCreatedAllOfDataFromJSON(json['data']),
    };
}

export function StoreOrderRefundCreatedAllOfToJSON(value?: StoreOrderRefundCreatedAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': StoreOrderRefundCreatedAllOfDataToJSON(value.data),
    };
}


