/* tslint:disable */
/* eslint-disable */
/**
 * Webhooks v3
 * Get notified when specific events occur on a BigCommerce store. For more information, see [Webhooks Overview](https://developer.bigcommerce.com/api-docs/store-management/webhooks/overview).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    StoreOrderStatusUpdatedAllOfData,
    StoreOrderStatusUpdatedAllOfDataFromJSON,
    StoreOrderStatusUpdatedAllOfDataFromJSONTyped,
    StoreOrderStatusUpdatedAllOfDataToJSON,
} from './';

/**
 * A lightweight description of the event that triggered the webhook. Will vary depending on the event registered.
 * @export
 * @interface StoreOrderStatusUpdatedAllOf
 */
export interface StoreOrderStatusUpdatedAllOf {
    /**
     * 
     * @type {StoreOrderStatusUpdatedAllOfData}
     * @memberof StoreOrderStatusUpdatedAllOf
     */
    data?: StoreOrderStatusUpdatedAllOfData;
}

export function StoreOrderStatusUpdatedAllOfFromJSON(json: any): StoreOrderStatusUpdatedAllOf {
    return StoreOrderStatusUpdatedAllOfFromJSONTyped(json, false);
}

export function StoreOrderStatusUpdatedAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): StoreOrderStatusUpdatedAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': !exists(json, 'data') ? undefined : StoreOrderStatusUpdatedAllOfDataFromJSON(json['data']),
    };
}

export function StoreOrderStatusUpdatedAllOfToJSON(value?: StoreOrderStatusUpdatedAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': StoreOrderStatusUpdatedAllOfDataToJSON(value.data),
    };
}


