/* tslint:disable */
/* eslint-disable */
/**
 * Webhooks v3
 * Get notified when specific events occur on a BigCommerce store. For more information, see [Webhooks Overview](https://developer.bigcommerce.com/api-docs/store-management/webhooks/overview).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Subscribe to all `store/customer` events
 * @export
 * @interface StoreCustomerWildcard
 */
export interface StoreCustomerWildcard {
}

export function StoreCustomerWildcardFromJSON(json: any): StoreCustomerWildcard {
    return StoreCustomerWildcardFromJSONTyped(json, false);
}

export function StoreCustomerWildcardFromJSONTyped(json: any, ignoreDiscriminator: boolean): StoreCustomerWildcard {
    return json;
}

export function StoreCustomerWildcardToJSON(value?: StoreCustomerWildcard | null): any {
    return value;
}


