/* tslint:disable */
/* eslint-disable */
/**
 * Webhooks v3
 * Get notified when specific events occur on a BigCommerce store. For more information, see [Webhooks Overview](https://developer.bigcommerce.com/api-docs/store-management/webhooks/overview).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    StoreCustomerPaymentInstrumentDefaultUpdatedAllOfData,
    StoreCustomerPaymentInstrumentDefaultUpdatedAllOfDataFromJSON,
    StoreCustomerPaymentInstrumentDefaultUpdatedAllOfDataFromJSONTyped,
    StoreCustomerPaymentInstrumentDefaultUpdatedAllOfDataToJSON,
} from './';

/**
 * A lightweight description of the event that triggered the webhook. Will vary depending on the event registered.
 * @export
 * @interface StoreCustomerPaymentInstrumentDefaultUpdatedAllOf
 */
export interface StoreCustomerPaymentInstrumentDefaultUpdatedAllOf {
    /**
     * 
     * @type {StoreCustomerPaymentInstrumentDefaultUpdatedAllOfData}
     * @memberof StoreCustomerPaymentInstrumentDefaultUpdatedAllOf
     */
    data?: StoreCustomerPaymentInstrumentDefaultUpdatedAllOfData;
}

export function StoreCustomerPaymentInstrumentDefaultUpdatedAllOfFromJSON(json: any): StoreCustomerPaymentInstrumentDefaultUpdatedAllOf {
    return StoreCustomerPaymentInstrumentDefaultUpdatedAllOfFromJSONTyped(json, false);
}

export function StoreCustomerPaymentInstrumentDefaultUpdatedAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): StoreCustomerPaymentInstrumentDefaultUpdatedAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': !exists(json, 'data') ? undefined : StoreCustomerPaymentInstrumentDefaultUpdatedAllOfDataFromJSON(json['data']),
    };
}

export function StoreCustomerPaymentInstrumentDefaultUpdatedAllOfToJSON(value?: StoreCustomerPaymentInstrumentDefaultUpdatedAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': StoreCustomerPaymentInstrumentDefaultUpdatedAllOfDataToJSON(value.data),
    };
}


