/* tslint:disable */
/* eslint-disable */
/**
 * Webhooks v3
 * Get notified when specific events occur on a BigCommerce store. For more information, see [Webhooks Overview](https://developer.bigcommerce.com/api-docs/store-management/webhooks/overview).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StoreCustomerAddressCreatedAllOfDataAddress
 */
export interface StoreCustomerAddressCreatedAllOfDataAddress {
    /**
     * ID of the customer
     * @type {number}
     * @memberof StoreCustomerAddressCreatedAllOfDataAddress
     */
    customerId?: number;
}

export function StoreCustomerAddressCreatedAllOfDataAddressFromJSON(json: any): StoreCustomerAddressCreatedAllOfDataAddress {
    return StoreCustomerAddressCreatedAllOfDataAddressFromJSONTyped(json, false);
}

export function StoreCustomerAddressCreatedAllOfDataAddressFromJSONTyped(json: any, ignoreDiscriminator: boolean): StoreCustomerAddressCreatedAllOfDataAddress {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'customerId': !exists(json, 'customer_id') ? undefined : json['customer_id'],
    };
}

export function StoreCustomerAddressCreatedAllOfDataAddressToJSON(value?: StoreCustomerAddressCreatedAllOfDataAddress | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'customer_id': value.customerId,
    };
}


