/* tslint:disable */
/* eslint-disable */
/**
 * Webhooks v3
 * Get notified when specific events occur on a BigCommerce store. For more information, see [Webhooks Overview](https://developer.bigcommerce.com/api-docs/store-management/webhooks/overview).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    StoreOrderCreatedAllOfData,
    StoreOrderCreatedAllOfDataFromJSON,
    StoreOrderCreatedAllOfDataFromJSONTyped,
    StoreOrderCreatedAllOfDataToJSON,
} from './';

/**
 * A lightweight description of the event that triggered the webhook. Will vary depending on the event registered.
 * @export
 * @interface StoreOrderCreatedAllOf
 */
export interface StoreOrderCreatedAllOf {
    /**
     * 
     * @type {StoreOrderCreatedAllOfData}
     * @memberof StoreOrderCreatedAllOf
     */
    data?: StoreOrderCreatedAllOfData;
}

export function StoreOrderCreatedAllOfFromJSON(json: any): StoreOrderCreatedAllOf {
    return StoreOrderCreatedAllOfFromJSONTyped(json, false);
}

export function StoreOrderCreatedAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): StoreOrderCreatedAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': !exists(json, 'data') ? undefined : StoreOrderCreatedAllOfDataFromJSON(json['data']),
    };
}

export function StoreOrderCreatedAllOfToJSON(value?: StoreOrderCreatedAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': StoreOrderCreatedAllOfDataToJSON(value.data),
    };
}


