/* tslint:disable */
/* eslint-disable */
/**
 * Email Templates
 * Manage Handlebars-based email templates globally and create channel-specific overrides.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ErrorResponseAllOf
 */
export interface ErrorResponseAllOf {
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof ErrorResponseAllOf
     */
    errors?: { [key: string]: string; };
}

export function ErrorResponseAllOfFromJSON(json: any): ErrorResponseAllOf {
    return ErrorResponseAllOfFromJSONTyped(json, false);
}

export function ErrorResponseAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): ErrorResponseAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'errors': !exists(json, 'errors') ? undefined : json['errors'],
    };
}

export function ErrorResponseAllOfToJSON(value?: ErrorResponseAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'errors': value.errors,
    };
}


