/* tslint:disable */
/* eslint-disable */
/**
 * Email Templates
 * Manage Handlebars-based email templates globally and create channel-specific overrides.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Scratch
 */
export interface Scratch {
    /**
     * 
     * @type {string}
     * @memberof Scratch
     */
    id?: string;
}

export function ScratchFromJSON(json: any): Scratch {
    return ScratchFromJSONTyped(json, false);
}

export function ScratchFromJSONTyped(json: any, ignoreDiscriminator: boolean): Scratch {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
    };
}

export function ScratchToJSON(value?: Scratch | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
    };
}


