/* tslint:disable */
/* eslint-disable */
/**
 * Settings V3
 * Manage settings and configuration for BigCommerce hosted stores and headless storefronts.  ## Authentication  Authenticate requests by including an [OAuth](https://developer.bigcommerce.com/api-docs/getting-started/authentication) `access_token` in the request header.  ```http GET /stores/{{STORE_HASH}}/v3/settings/storefront/status host: api.bigcommerce.com Accept: application/json X-Auth-Token: {{ACCESS_TOKEN}} ```  ### OAuth Scopes |  **UI Name** | **Permission** | **Parameter** | |-|-|-| |  Information & Settings | modify | `store_v2_information` | |  Information & Settings | read-only | `store_v2_information_read_only` |
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: support@bigcommerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LogoSettings
 */
export interface LogoSettings {
    /**
     * 
     * @type {string}
     * @memberof LogoSettings
     */
    logoImageUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof LogoSettings
     */
    logoText?: string;
    /**
     * 
     * @type {string}
     * @memberof LogoSettings
     */
    type?: LogoSettingsTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof LogoSettings
     */
    faviconUrl?: string;
}

/**
* @export
* @enum {string}
*/
export enum LogoSettingsTypeEnum {
    Image = 'image',
    Text = 'text'
}

export function LogoSettingsFromJSON(json: any): LogoSettings {
    return LogoSettingsFromJSONTyped(json, false);
}

export function LogoSettingsFromJSONTyped(json: any, ignoreDiscriminator: boolean): LogoSettings {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'logoImageUrl': !exists(json, 'logo_image_url') ? undefined : json['logo_image_url'],
        'logoText': !exists(json, 'logo_text') ? undefined : json['logo_text'],
        'type': !exists(json, 'type') ? undefined : json['type'],
        'faviconUrl': !exists(json, 'favicon_url') ? undefined : json['favicon_url'],
    };
}

export function LogoSettingsToJSON(value?: LogoSettings | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'logo_image_url': value.logoImageUrl,
        'logo_text': value.logoText,
        'type': value.type,
        'favicon_url': value.faviconUrl,
    };
}


