/* tslint:disable */
/* eslint-disable */
/**
 * Settings V3
 * Manage settings and configuration for BigCommerce hosted stores and headless storefronts.  ## Authentication  Authenticate requests by including an [OAuth](https://developer.bigcommerce.com/api-docs/getting-started/authentication) `access_token` in the request header.  ```http GET /stores/{{STORE_HASH}}/v3/settings/storefront/status host: api.bigcommerce.com Accept: application/json X-Auth-Token: {{ACCESS_TOKEN}} ```  ### OAuth Scopes |  **UI Name** | **Permission** | **Parameter** | |-|-|-| |  Information & Settings | modify | `store_v2_information` | |  Information & Settings | read-only | `store_v2_information_read_only` |
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: support@bigcommerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StorefrontStatus
 */
export interface StorefrontStatus {
    /**
     * 
     * @type {string}
     * @memberof StorefrontStatus
     */
    downForMaintenanceMessage?: string;
    /**
     * 
     * @type {string}
     * @memberof StorefrontStatus
     */
    prelaunchMessage?: string;
    /**
     * A read-only value representing the auto-generated storefront password.
     * @type {string}
     * @memberof StorefrontStatus
     */
    prelaunchPassword?: string;
}

export function StorefrontStatusFromJSON(json: any): StorefrontStatus {
    return StorefrontStatusFromJSONTyped(json, false);
}

export function StorefrontStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): StorefrontStatus {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'downForMaintenanceMessage': !exists(json, 'down_for_maintenance_message') ? undefined : json['down_for_maintenance_message'],
        'prelaunchMessage': !exists(json, 'prelaunch_message') ? undefined : json['prelaunch_message'],
        'prelaunchPassword': !exists(json, 'prelaunch_password') ? undefined : json['prelaunch_password'],
    };
}

export function StorefrontStatusToJSON(value?: StorefrontStatus | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'down_for_maintenance_message': value.downForMaintenanceMessage,
        'prelaunch_message': value.prelaunchMessage,
        'prelaunch_password': value.prelaunchPassword,
    };
}


