/* tslint:disable */
/* eslint-disable */
/**
 * Content
 * Manage blog posts, blog tags, content pages, and redirects.  <div class=\"HubBlock--callout\"> <div class=\"CalloutBlock--warning\"> <div class=\"HubBlock-content\">  ### Note * Redirects V2 are deprecated; use [V3 Redirects](https://developer.bigcommerce.com/api-reference/storefront/redirects/redirects/getredirects) instead. * Pages V2 are deprecated; use [Pages V3](https://developer.bigcommerce.com/api-reference/store-management/pages) instead.   </div> </div> </div>
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Addresses
 */
export interface Addresses {
    /**
     * Full URL of where the resource is located.
     * @type {string}
     * @memberof Addresses
     */
    url?: string;
    /**
     * Resource being accessed.
     * @type {string}
     * @memberof Addresses
     */
    resource?: string;
}

export function AddressesFromJSON(json: any): Addresses {
    return AddressesFromJSONTyped(json, false);
}

export function AddressesFromJSONTyped(json: any, ignoreDiscriminator: boolean): Addresses {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'url': !exists(json, 'url') ? undefined : json['url'],
        'resource': !exists(json, 'resource') ? undefined : json['resource'],
    };
}

export function AddressesToJSON(value?: Addresses | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'url': value.url,
        'resource': value.resource,
    };
}


