export const BIGCOMMERCE_GUEST_WISHLIST_KEY = 'bigcommerce-wishlist';
export const BIGCOMMERCE_GUEST_CUSTOMER_ID = 0;
export const BIGCOMMERCE_GUEST_WISHLIST_ID = 0;
export const BIGCOMMERCE_GUEST_WISHLIST_TOKEN = '';
export const BIGCOMMERCE_COOKIE_MAXAGE = 60 * 60 * 24 * 7;
