/* tslint:disable */
/* eslint-disable */
/**
 * Pages V3
 * Manage content pages across multiple sites.
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ContactFieldsAllOf,
    ContactFieldsAllOfFromJSON,
    ContactFieldsAllOfFromJSONTyped,
    ContactFieldsAllOfToJSON,
} from './';

/**
 * 
 * @export
 * @interface ContactFields
 */
export interface ContactFields {
    /**
     * Full name of the customer submitting the form.
     * @type {string}
     * @memberof ContactFields
     */
    fullname?: string;
    /**
     * Customer’s phone number, as submitted on the form.
     * @type {string}
     * @memberof ContactFields
     */
    phone?: string;
    /**
     * Customer’s submitted company name.
     * @type {string}
     * @memberof ContactFields
     */
    companyname?: string;
    /**
     * Customer’s submitted order number.
     * @type {string}
     * @memberof ContactFields
     */
    orderno?: string;
    /**
     * Customer’s submitted RMA (Return Merchandise Authorization) number.
     * @type {string}
     * @memberof ContactFields
     */
    rma?: string;
}

export function ContactFieldsFromJSON(json: any): ContactFields {
    return ContactFieldsFromJSONTyped(json, false);
}

export function ContactFieldsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContactFields {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'fullname': !exists(json, 'fullname') ? undefined : json['fullname'],
        'phone': !exists(json, 'phone') ? undefined : json['phone'],
        'companyname': !exists(json, 'companyname') ? undefined : json['companyname'],
        'orderno': !exists(json, 'orderno') ? undefined : json['orderno'],
        'rma': !exists(json, 'rma') ? undefined : json['rma'],
    };
}

export function ContactFieldsToJSON(value?: ContactFields | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'fullname': value.fullname,
        'phone': value.phone,
        'companyname': value.companyname,
        'orderno': value.orderno,
        'rma': value.rma,
    };
}


