/* tslint:disable */
/* eslint-disable */
/**
 * Pages V3
 * Manage content pages across multiple sites.
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Common Page properties.
 * @export
 * @interface PageBase
 */
export interface PageBase {
    /**
     * The name of the page. Must be unique.
     * @type {string}
     * @memberof PageBase
     */
    name: string;
    /**
     * Determines the visibility of the page in the storefront’s navigation menu.
     * @type {boolean}
     * @memberof PageBase
     */
    isVisible?: boolean;
    /**
     * ID of any parent Web page.
     * @type {number}
     * @memberof PageBase
     */
    parentId?: number;
    /**
     * Determines the order in which the page is displayed on the storefront. (Lower integers specify earlier display.)
     * @type {number}
     * @memberof PageBase
     */
    sortOrder?: number;
    /**
     * Determines the type of the page.
     * 
     * |Value|Description|
     * |-|-|
     * |`contact_form`|when the store’s contact form is used|
     * |`link`|link to another web address|
     * |`page`|free-text page|
     * |`raw`|raw page|
     * |`rss_feed`|syndicated content from an RSS feed|
     * @type {string}
     * @memberof PageBase
     */
    type: string;
    /**
     * Determines whether this page is the storefront’s home page.
     * @type {boolean}
     * @memberof PageBase
     */
    isHomepage?: boolean;
    /**
     * If `true`, this will be displayed as a home page.
     * @type {boolean}
     * @memberof PageBase
     */
    isCustomersOnly?: boolean;
}

export function PageBaseFromJSON(json: any): PageBase {
    return PageBaseFromJSONTyped(json, false);
}

export function PageBaseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PageBase {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'isVisible': !exists(json, 'is_visible') ? undefined : json['is_visible'],
        'parentId': !exists(json, 'parent_id') ? undefined : json['parent_id'],
        'sortOrder': !exists(json, 'sort_order') ? undefined : json['sort_order'],
        'type': json['type'],
        'isHomepage': !exists(json, 'is_homepage') ? undefined : json['is_homepage'],
        'isCustomersOnly': !exists(json, 'is_customers_only') ? undefined : json['is_customers_only'],
    };
}

export function PageBaseToJSON(value?: PageBase | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'is_visible': value.isVisible,
        'parent_id': value.parentId,
        'sort_order': value.sortOrder,
        'type': value.type,
        'is_homepage': value.isHomepage,
        'is_customers_only': value.isCustomersOnly,
    };
}


