/* tslint:disable */
/* eslint-disable */
/**
 * Storefront Orders
 * Get order data immediately after an order is placed on the storefront.
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AppliedDiscount
 */
export interface AppliedDiscount {
    /**
     * The name provided by the merchant.
     * @type {string}
     * @memberof AppliedDiscount
     */
    name?: string;
    /**
     * The discounted amount applied within a given context.
     * @type {number}
     * @memberof AppliedDiscount
     */
    discountedAmount?: number;
}

export function AppliedDiscountFromJSON(json: any): AppliedDiscount {
    return AppliedDiscountFromJSONTyped(json, false);
}

export function AppliedDiscountFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppliedDiscount {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'discountedAmount': !exists(json, 'discountedAmount') ? undefined : json['discountedAmount'],
    };
}

export function AppliedDiscountToJSON(value?: AppliedDiscount | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'discountedAmount': value.discountedAmount,
    };
}


