/* tslint:disable */
/* eslint-disable */
/**
 * Storefront Orders
 * Get order data immediately after an order is placed on the storefront.
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AppliedCoupon
 */
export interface AppliedCoupon {
    /**
     * The coupon ID.
     * @type {string}
     * @memberof AppliedCoupon
     */
    id?: string;
    /**
     * the coupon code
     * @type {string}
     * @memberof AppliedCoupon
     */
    code: string;
    /**
     * The coupon title based on different types provided in control panel section
     * @type {string}
     * @memberof AppliedCoupon
     */
    displayName?: string;
    /**
     * Key name to identify the type of coupon.
     * @type {string}
     * @memberof AppliedCoupon
     */
    couponType?: string;
    /**
     * The discounted amount applied within a given context.
     * @type {number}
     * @memberof AppliedCoupon
     */
    discountedAmount?: number;
}

export function AppliedCouponFromJSON(json: any): AppliedCoupon {
    return AppliedCouponFromJSONTyped(json, false);
}

export function AppliedCouponFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppliedCoupon {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'code': json['code'],
        'displayName': !exists(json, 'displayName') ? undefined : json['displayName'],
        'couponType': !exists(json, 'couponType') ? undefined : json['couponType'],
        'discountedAmount': !exists(json, 'discountedAmount') ? undefined : json['discountedAmount'],
    };
}

export function AppliedCouponToJSON(value?: AppliedCoupon | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'code': value.code,
        'displayName': value.displayName,
        'couponType': value.couponType,
        'discountedAmount': value.discountedAmount,
    };
}


