/* tslint:disable */
/* eslint-disable */
/**
 * Storefront Orders
 * Get order data immediately after an order is placed on the storefront.
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    OrderNateBillingAddress,
    OrderNateBillingAddressFromJSON,
    OrderNateBillingAddressFromJSONTyped,
    OrderNateBillingAddressToJSON,
    OrderNateCurrency,
    OrderNateCurrencyFromJSON,
    OrderNateCurrencyFromJSONTyped,
    OrderNateCurrencyToJSON,
    OrderNateLineItems,
    OrderNateLineItemsFromJSON,
    OrderNateLineItemsFromJSONTyped,
    OrderNateLineItemsToJSON,
    OrderTaxes,
    OrderTaxesFromJSON,
    OrderTaxesFromJSONTyped,
    OrderTaxesToJSON,
} from './';

/**
 * 
 * @export
 * @interface OrderNate
 */
export interface OrderNate {
    /**
     * 
     * @type {number}
     * @memberof OrderNate
     */
    orderId?: number;
    /**
     * 
     * @type {string}
     * @memberof OrderNate
     */
    cartId?: string;
    /**
     * 
     * @type {OrderNateCurrency}
     * @memberof OrderNate
     */
    currency?: OrderNateCurrency;
    /**
     * 
     * @type {boolean}
     * @memberof OrderNate
     */
    isTaxIncluded?: boolean;
    /**
     * 
     * @type {number}
     * @memberof OrderNate
     */
    baseAmount?: number;
    /**
     * 
     * @type {number}
     * @memberof OrderNate
     */
    discountAmount?: number;
    /**
     * 
     * @type {number}
     * @memberof OrderNate
     */
    orderAmount?: number;
    /**
     * 
     * @type {number}
     * @memberof OrderNate
     */
    orderAmountAsInteger?: number;
    /**
     * 
     * @type {number}
     * @memberof OrderNate
     */
    shippingCostTotal?: number;
    /**
     * 
     * @type {number}
     * @memberof OrderNate
     */
    shippingCostBeforeDiscount?: number;
    /**
     * 
     * @type {number}
     * @memberof OrderNate
     */
    handlingCostTotal?: number;
    /**
     * 
     * @type {Array<object>}
     * @memberof OrderNate
     */
    coupons?: Array<object>;
    /**
     * 
     * @type {OrderNateLineItems}
     * @memberof OrderNate
     */
    lineItems?: OrderNateLineItems;
    /**
     * 
     * @type {number}
     * @memberof OrderNate
     */
    customerId?: number;
    /**
     * 
     * @type {OrderNateBillingAddress}
     * @memberof OrderNate
     */
    billingAddress?: OrderNateBillingAddress;
    /**
     * 
     * @type {string}
     * @memberof OrderNate
     */
    status?: string;
    /**
     * 
     * @type {boolean}
     * @memberof OrderNate
     */
    customerCanBeCreated?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof OrderNate
     */
    hasDigitalItems?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof OrderNate
     */
    isDownloadable?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof OrderNate
     */
    isComplete?: boolean;
    /**
     * 
     * @type {string}
     * @memberof OrderNate
     */
    customerMessage?: string;
    /**
     * 
     * @type {Array<OrderTaxes>}
     * @memberof OrderNate
     */
    taxes?: Array<OrderTaxes>;
    /**
     * 
     * @type {number}
     * @memberof OrderNate
     */
    taxTotal?: number;
}

export function OrderNateFromJSON(json: any): OrderNate {
    return OrderNateFromJSONTyped(json, false);
}

export function OrderNateFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrderNate {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'orderId': !exists(json, 'orderId') ? undefined : json['orderId'],
        'cartId': !exists(json, 'cartId') ? undefined : json['cartId'],
        'currency': !exists(json, 'currency') ? undefined : OrderNateCurrencyFromJSON(json['currency']),
        'isTaxIncluded': !exists(json, 'isTaxIncluded') ? undefined : json['isTaxIncluded'],
        'baseAmount': !exists(json, 'baseAmount') ? undefined : json['baseAmount'],
        'discountAmount': !exists(json, 'discountAmount') ? undefined : json['discountAmount'],
        'orderAmount': !exists(json, 'orderAmount') ? undefined : json['orderAmount'],
        'orderAmountAsInteger': !exists(json, 'orderAmountAsInteger') ? undefined : json['orderAmountAsInteger'],
        'shippingCostTotal': !exists(json, 'shippingCostTotal') ? undefined : json['shippingCostTotal'],
        'shippingCostBeforeDiscount': !exists(json, 'shippingCostBeforeDiscount') ? undefined : json['shippingCostBeforeDiscount'],
        'handlingCostTotal': !exists(json, 'handlingCostTotal') ? undefined : json['handlingCostTotal'],
        'coupons': !exists(json, 'coupons') ? undefined : json['coupons'],
        'lineItems': !exists(json, 'lineItems') ? undefined : OrderNateLineItemsFromJSON(json['lineItems']),
        'customerId': !exists(json, 'customerId') ? undefined : json['customerId'],
        'billingAddress': !exists(json, 'billingAddress') ? undefined : OrderNateBillingAddressFromJSON(json['billingAddress']),
        'status': !exists(json, 'status') ? undefined : json['status'],
        'customerCanBeCreated': !exists(json, 'customerCanBeCreated') ? undefined : json['customerCanBeCreated'],
        'hasDigitalItems': !exists(json, 'hasDigitalItems') ? undefined : json['hasDigitalItems'],
        'isDownloadable': !exists(json, 'isDownloadable') ? undefined : json['isDownloadable'],
        'isComplete': !exists(json, 'isComplete') ? undefined : json['isComplete'],
        'customerMessage': !exists(json, 'customerMessage') ? undefined : json['customerMessage'],
        'taxes': !exists(json, 'taxes') ? undefined : ((json['taxes'] as Array<any>).map(OrderTaxesFromJSON)),
        'taxTotal': !exists(json, 'taxTotal') ? undefined : json['taxTotal'],
    };
}

export function OrderNateToJSON(value?: OrderNate | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'orderId': value.orderId,
        'cartId': value.cartId,
        'currency': OrderNateCurrencyToJSON(value.currency),
        'isTaxIncluded': value.isTaxIncluded,
        'baseAmount': value.baseAmount,
        'discountAmount': value.discountAmount,
        'orderAmount': value.orderAmount,
        'orderAmountAsInteger': value.orderAmountAsInteger,
        'shippingCostTotal': value.shippingCostTotal,
        'shippingCostBeforeDiscount': value.shippingCostBeforeDiscount,
        'handlingCostTotal': value.handlingCostTotal,
        'coupons': value.coupons,
        'lineItems': OrderNateLineItemsToJSON(value.lineItems),
        'customerId': value.customerId,
        'billingAddress': OrderNateBillingAddressToJSON(value.billingAddress),
        'status': value.status,
        'customerCanBeCreated': value.customerCanBeCreated,
        'hasDigitalItems': value.hasDigitalItems,
        'isDownloadable': value.isDownloadable,
        'isComplete': value.isComplete,
        'customerMessage': value.customerMessage,
        'taxes': value.taxes === undefined ? undefined : ((value.taxes as Array<any>).map(OrderTaxesToJSON)),
        'taxTotal': value.taxTotal,
    };
}


