/* tslint:disable */
/* eslint-disable */
/**
 * Themes
 * Backup, restore, download, and activate themes; and, get the status of theme jobs and read theme configurations.  - [OAuth Scopes](#oauth-scopes) - [Authentication](#authentication)  ## Authentication  Requests can be authenticated by sending an `access_token` via `X-Auth-Token` HTTP header.  ```http GET /stores/{$$.env.store_hash}/v3/themes host: api.bigcommerce.com Accept: application/json X-Auth-Token: {access_token} ```  ### OAuth Scopes | UI Name                                      | Permission | Parameter                                     | |----------------------------------------------|------------|-----------------------------------------------| | Themes                                       | modify     | `store_themes_manage`                         | For more information on OAuth Scopes, see: [Authentication](https://developer.bigcommerce.com/api-docs/getting-started/authentication).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface JobWarnings
 */
export interface JobWarnings {
    /**
     * The message.
     * @type {string}
     * @memberof JobWarnings
     */
    message?: string;
    /**
     * The warning.
     * @type {string}
     * @memberof JobWarnings
     */
    warning?: string;
}

export function JobWarningsFromJSON(json: any): JobWarnings {
    return JobWarningsFromJSONTyped(json, false);
}

export function JobWarningsFromJSONTyped(json: any, ignoreDiscriminator: boolean): JobWarnings {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'message': !exists(json, 'message') ? undefined : json['message'],
        'warning': !exists(json, 'warning') ? undefined : json['warning'],
    };
}

export function JobWarningsToJSON(value?: JobWarnings | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'message': value.message,
        'warning': value.warning,
    };
}


