/* tslint:disable */
/* eslint-disable */
/**
 * Themes
 * Backup, restore, download, and activate themes; and, get the status of theme jobs and read theme configurations.  - [OAuth Scopes](#oauth-scopes) - [Authentication](#authentication)  ## Authentication  Requests can be authenticated by sending an `access_token` via `X-Auth-Token` HTTP header.  ```http GET /stores/{$$.env.store_hash}/v3/themes host: api.bigcommerce.com Accept: application/json X-Auth-Token: {access_token} ```  ### OAuth Scopes | UI Name                                      | Permission | Parameter                                     | |----------------------------------------------|------------|-----------------------------------------------| | Themes                                       | modify     | `store_themes_manage`                         | For more information on OAuth Scopes, see: [Authentication](https://developer.bigcommerce.com/api-docs/getting-started/authentication).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * A variation.
 * @export
 * @interface Variation
 */
export interface Variation {
    /**
     * The description.
     * @type {string}
     * @memberof Variation
     */
    description?: string;
    /**
     * The external identifier.
     * @type {string}
     * @memberof Variation
     */
    externalId?: string;
    /**
     * The name.
     * @type {string}
     * @memberof Variation
     */
    name?: string;
    /**
     * The identifier.
     * @type {string}
     * @memberof Variation
     */
    uuid?: string;
}

export function VariationFromJSON(json: any): Variation {
    return VariationFromJSONTyped(json, false);
}

export function VariationFromJSONTyped(json: any, ignoreDiscriminator: boolean): Variation {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'description': !exists(json, 'description') ? undefined : json['description'],
        'externalId': !exists(json, 'external_id') ? undefined : json['external_id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'uuid': !exists(json, 'uuid') ? undefined : json['uuid'],
    };
}

export function VariationToJSON(value?: Variation | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'description': value.description,
        'external_id': value.externalId,
        'name': value.name,
        'uuid': value.uuid,
    };
}


