/* tslint:disable */
/* eslint-disable */
/**
 * Storefront Checkouts
 * Manage checkout operations and data via front-end JavaScript on BigCommerce stencil powered storefronts.
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Checkout,
    CheckoutFromJSON,
    CheckoutFromJSONTyped,
    CheckoutToJSON,
} from './';

/**
 * 
 * @export
 * @interface CheckoutsResp
 */
export interface CheckoutsResp {
    /**
     * 
     * @type {Checkout}
     * @memberof CheckoutsResp
     */
    data?: Checkout;
}

export function CheckoutsRespFromJSON(json: any): CheckoutsResp {
    return CheckoutsRespFromJSONTyped(json, false);
}

export function CheckoutsRespFromJSONTyped(json: any, ignoreDiscriminator: boolean): CheckoutsResp {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': !exists(json, 'data') ? undefined : CheckoutFromJSON(json['data']),
    };
}

export function CheckoutsRespToJSON(value?: CheckoutsResp | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': CheckoutToJSON(value.data),
    };
}


