/* tslint:disable */
/* eslint-disable */
/**
 * Storefront Checkouts
 * Manage checkout operations and data via front-end JavaScript on BigCommerce stencil powered storefronts.
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ConsignmentLineItem
 */
export interface ConsignmentLineItem {
    /**
     * 
     * @type {string}
     * @memberof ConsignmentLineItem
     */
    itemId: string;
    /**
     * 
     * @type {number}
     * @memberof ConsignmentLineItem
     */
    quantity: number;
}

export function ConsignmentLineItemFromJSON(json: any): ConsignmentLineItem {
    return ConsignmentLineItemFromJSONTyped(json, false);
}

export function ConsignmentLineItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConsignmentLineItem {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'itemId': json['itemId'],
        'quantity': json['quantity'],
    };
}

export function ConsignmentLineItemToJSON(value?: ConsignmentLineItem | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'itemId': value.itemId,
        'quantity': value.quantity,
    };
}


