/* tslint:disable */
/* eslint-disable */
/**
 * Storefront Checkouts
 * Manage checkout operations and data via front-end JavaScript on BigCommerce stencil powered storefronts.
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    AddressFull,
    AddressFullFromJSON,
    AddressFullFromJSONTyped,
    AddressFullToJSON,
    ConsignmentAvailableShippingOptions,
    ConsignmentAvailableShippingOptionsFromJSON,
    ConsignmentAvailableShippingOptionsFromJSONTyped,
    ConsignmentAvailableShippingOptionsToJSON,
    ConsignmentCouponDiscount,
    ConsignmentCouponDiscountFromJSON,
    ConsignmentCouponDiscountFromJSONTyped,
    ConsignmentCouponDiscountToJSON,
    ConsignmentDiscount,
    ConsignmentDiscountFromJSON,
    ConsignmentDiscountFromJSONTyped,
    ConsignmentDiscountToJSON,
    SelectedShippingOption,
    SelectedShippingOptionFromJSON,
    SelectedShippingOptionFromJSONTyped,
    SelectedShippingOptionToJSON,
} from './';

/**
 * This allows us to have multiple shipping addresses. Where there is only one shipping address, this array will contain only one value, with all the items.
 * @export
 * @interface ConsignmentFull
 */
export interface ConsignmentFull {
    /**
     * 
     * @type {string}
     * @memberof ConsignmentFull
     */
    id?: string;
    /**
     * 
     * @type {AddressFull}
     * @memberof ConsignmentFull
     */
    shippingAddress?: AddressFull;
    /**
     * This is available only when "include=consignments.availableShippingOptions" is presented in the URL.
     * @type {Array<ConsignmentAvailableShippingOptions>}
     * @memberof ConsignmentFull
     */
    availableShippingOptions?: Array<ConsignmentAvailableShippingOptions>;
    /**
     * 
     * @type {SelectedShippingOption}
     * @memberof ConsignmentFull
     */
    selectedShippingOption?: SelectedShippingOption;
    /**
     * List of consignment discounts applied through coupons
     * @type {Array<ConsignmentCouponDiscount>}
     * @memberof ConsignmentFull
     */
    couponDiscounts?: Array<ConsignmentCouponDiscount>;
    /**
     * List of consignment discounts applied through cart level discounts
     * @type {Array<ConsignmentDiscount>}
     * @memberof ConsignmentFull
     */
    discounts?: Array<ConsignmentDiscount>;
    /**
     * The shipping cost for this consignment.
     * @type {number}
     * @memberof ConsignmentFull
     */
    shippingCost?: number;
    /**
     * The handling cost of shipping for this consignment.
     * @type {number}
     * @memberof ConsignmentFull
     */
    handlingCost?: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof ConsignmentFull
     */
    lineItemIds?: Array<string>;
}

export function ConsignmentFullFromJSON(json: any): ConsignmentFull {
    return ConsignmentFullFromJSONTyped(json, false);
}

export function ConsignmentFullFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConsignmentFull {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'shippingAddress': !exists(json, 'shippingAddress') ? undefined : AddressFullFromJSON(json['shippingAddress']),
        'availableShippingOptions': !exists(json, 'availableShippingOptions') ? undefined : ((json['availableShippingOptions'] as Array<any>).map(ConsignmentAvailableShippingOptionsFromJSON)),
        'selectedShippingOption': !exists(json, 'selectedShippingOption') ? undefined : SelectedShippingOptionFromJSON(json['selectedShippingOption']),
        'couponDiscounts': !exists(json, 'couponDiscounts') ? undefined : ((json['couponDiscounts'] as Array<any>).map(ConsignmentCouponDiscountFromJSON)),
        'discounts': !exists(json, 'discounts') ? undefined : ((json['discounts'] as Array<any>).map(ConsignmentDiscountFromJSON)),
        'shippingCost': !exists(json, 'shippingCost') ? undefined : json['shippingCost'],
        'handlingCost': !exists(json, 'handlingCost') ? undefined : json['handlingCost'],
        'lineItemIds': !exists(json, 'lineItemIds') ? undefined : json['lineItemIds'],
    };
}

export function ConsignmentFullToJSON(value?: ConsignmentFull | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'shippingAddress': AddressFullToJSON(value.shippingAddress),
        'availableShippingOptions': value.availableShippingOptions === undefined ? undefined : ((value.availableShippingOptions as Array<any>).map(ConsignmentAvailableShippingOptionsToJSON)),
        'selectedShippingOption': SelectedShippingOptionToJSON(value.selectedShippingOption),
        'couponDiscounts': value.couponDiscounts === undefined ? undefined : ((value.couponDiscounts as Array<any>).map(ConsignmentCouponDiscountToJSON)),
        'discounts': value.discounts === undefined ? undefined : ((value.discounts as Array<any>).map(ConsignmentDiscountToJSON)),
        'shippingCost': value.shippingCost,
        'handlingCost': value.handlingCost,
        'lineItemIds': value.lineItemIds,
    };
}


