/* tslint:disable */
/* eslint-disable */
/**
 * Storefront Checkouts
 * Manage checkout operations and data via front-end JavaScript on BigCommerce stencil powered storefronts.
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    AppliedDiscount,
    AppliedDiscountFromJSON,
    AppliedDiscountFromJSONTyped,
    AppliedDiscountToJSON,
} from './';

/**
 * 
 * @export
 * @interface ItemDigital
 */
export interface ItemDigital {
    /**
     * The line-item ID.
     * @type {string}
     * @memberof ItemDigital
     */
    id?: string;
    /**
     * Bundled items will have their parent's item Id.
     * @type {string}
     * @memberof ItemDigital
     */
    parentId?: string;
    /**
     * ID of the variant.
     * @type {number}
     * @memberof ItemDigital
     */
    variantId?: number;
    /**
     * ID of the product.
     * @type {number}
     * @memberof ItemDigital
     */
    productId?: number;
    /**
     * SKU of the variant.
     * @type {string}
     * @memberof ItemDigital
     */
    sku?: string;
    /**
     * The item's product name.
     * @type {string}
     * @memberof ItemDigital
     */
    name?: string;
    /**
     * The product URL.
     * @type {string}
     * @memberof ItemDigital
     */
    url?: string;
    /**
     * Quantity of this item.
     * @type {number}
     * @memberof ItemDigital
     */
    quantity: number;
    /**
     * The item's brand.
     * @type {string}
     * @memberof ItemDigital
     */
    brand?: string;
    /**
     * Whether the item is taxable.
     * @type {boolean}
     * @memberof ItemDigital
     */
    isTaxable?: boolean;
    /**
     * URL of an image of this item, accessible on the internet.
     * @type {string}
     * @memberof ItemDigital
     */
    imageUrl?: string;
    /**
     * List of discounts applied to this item, as an array of AppliedDiscount objects.
     * @type {Array<AppliedDiscount>}
     * @memberof ItemDigital
     */
    discounts?: Array<AppliedDiscount>;
    /**
     * The total value of all discounts applied to this item (excluding coupon).
     * @type {number}
     * @memberof ItemDigital
     */
    discountAmount?: number;
    /**
     * The total value of all coupons applied to this item.
     * @type {number}
     * @memberof ItemDigital
     */
    couponAmount?: number;
    /**
     * Item's list price, as quoted by the manufacturer/distributor.
     * @type {number}
     * @memberof ItemDigital
     */
    listPrice?: number;
    /**
     * Item's price after all discounts are applied. (The final price before tax calculation.)
     * @type {number}
     * @memberof ItemDigital
     */
    salePrice?: number;
    /**
     * Item's list price multiplied by the quantity.
     * @type {number}
     * @memberof ItemDigital
     */
    extendedListPrice?: number;
    /**
     * Item's sale price multiplied by the quantity.
     * @type {number}
     * @memberof ItemDigital
     */
    extendedSalePrice?: number;
    /**
     * the product type - physical or digital
     * @type {string}
     * @memberof ItemDigital
     */
    type?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ItemDigital
     */
    isMutable?: boolean;
    /**
     * Whether this item requires shipping to a physical address.
     * @type {boolean}
     * @memberof ItemDigital
     */
    isShippingRequired?: boolean;
    /**
     * URLs to download all product files.
     * @type {Array<string>}
     * @memberof ItemDigital
     */
    downloadFileUrls?: Array<string>;
    /**
     * The URL for the combined downloads page.
     * @type {string}
     * @memberof ItemDigital
     */
    downloadPageUrl?: string;
    /**
     * Combined download size, in human-readable style. E.g.: `30MB`.
     * @type {string}
     * @memberof ItemDigital
     */
    downloadSize?: string;
}

export function ItemDigitalFromJSON(json: any): ItemDigital {
    return ItemDigitalFromJSONTyped(json, false);
}

export function ItemDigitalFromJSONTyped(json: any, ignoreDiscriminator: boolean): ItemDigital {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'parentId': !exists(json, 'parentId') ? undefined : json['parentId'],
        'variantId': !exists(json, 'variantId') ? undefined : json['variantId'],
        'productId': !exists(json, 'productId') ? undefined : json['productId'],
        'sku': !exists(json, 'sku') ? undefined : json['sku'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'url': !exists(json, 'url') ? undefined : json['url'],
        'quantity': json['quantity'],
        'brand': !exists(json, 'brand') ? undefined : json['brand'],
        'isTaxable': !exists(json, 'isTaxable') ? undefined : json['isTaxable'],
        'imageUrl': !exists(json, 'imageUrl') ? undefined : json['imageUrl'],
        'discounts': !exists(json, 'discounts') ? undefined : ((json['discounts'] as Array<any>).map(AppliedDiscountFromJSON)),
        'discountAmount': !exists(json, 'discountAmount') ? undefined : json['discountAmount'],
        'couponAmount': !exists(json, 'couponAmount') ? undefined : json['couponAmount'],
        'listPrice': !exists(json, 'listPrice') ? undefined : json['listPrice'],
        'salePrice': !exists(json, 'salePrice') ? undefined : json['salePrice'],
        'extendedListPrice': !exists(json, 'extendedListPrice') ? undefined : json['extendedListPrice'],
        'extendedSalePrice': !exists(json, 'extendedSalePrice') ? undefined : json['extendedSalePrice'],
        'type': !exists(json, 'type') ? undefined : json['type'],
        'isMutable': !exists(json, 'isMutable') ? undefined : json['isMutable'],
        'isShippingRequired': !exists(json, 'isShippingRequired') ? undefined : json['isShippingRequired'],
        'downloadFileUrls': !exists(json, 'downloadFileUrls') ? undefined : json['downloadFileUrls'],
        'downloadPageUrl': !exists(json, 'downloadPageUrl') ? undefined : json['downloadPageUrl'],
        'downloadSize': !exists(json, 'downloadSize') ? undefined : json['downloadSize'],
    };
}

export function ItemDigitalToJSON(value?: ItemDigital | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'parentId': value.parentId,
        'variantId': value.variantId,
        'productId': value.productId,
        'sku': value.sku,
        'name': value.name,
        'url': value.url,
        'quantity': value.quantity,
        'brand': value.brand,
        'isTaxable': value.isTaxable,
        'imageUrl': value.imageUrl,
        'discounts': value.discounts === undefined ? undefined : ((value.discounts as Array<any>).map(AppliedDiscountToJSON)),
        'discountAmount': value.discountAmount,
        'couponAmount': value.couponAmount,
        'listPrice': value.listPrice,
        'salePrice': value.salePrice,
        'extendedListPrice': value.extendedListPrice,
        'extendedSalePrice': value.extendedSalePrice,
        'type': value.type,
        'isMutable': value.isMutable,
        'isShippingRequired': value.isShippingRequired,
        'downloadFileUrls': value.downloadFileUrls,
        'downloadPageUrl': value.downloadPageUrl,
        'downloadSize': value.downloadSize,
    };
}


