/* tslint:disable */
/* eslint-disable */
/**
 * Shipping V3
 * V3 REST API shipping endpoints.
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ShippingMethodFullAllOf
 */
export interface ShippingMethodFullAllOf {
    /**
     * Shipping-method ID. READ-ONLY
     * @type {number}
     * @memberof ShippingMethodFullAllOf
     */
    id?: number;
}

export function ShippingMethodFullAllOfFromJSON(json: any): ShippingMethodFullAllOf {
    return ShippingMethodFullAllOfFromJSONTyped(json, false);
}

export function ShippingMethodFullAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): ShippingMethodFullAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
    };
}

export function ShippingMethodFullAllOfToJSON(value?: ShippingMethodFullAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
    };
}


