/* tslint:disable */
/* eslint-disable */
/**
 * Shipping V2
 * Manage shipping zones, shipping methods, and shipping carrier connections.  ### Shipping Zones The Shipping Zone object and endpoints manage shipping zones within countries.  ### Shipping Methods The Shipping Methods object and endpoints manage shipping rules within Shipping Zones. These rules determine the shipping rates displayed at checkout, and related parts of the control panel, such as the shipping of manual orders.  ### Shipping Carrier Connections Carrier connections refer to specific settings required to connect to a specific shipping carrier. Each carrier requires your app to supply a unique set of properties/fields to establish a connection with that carrier.
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Depends on the shipping-method type. See the [supported settings object](#supported-settings).
 * @export
 * @interface ShippingMethodBaseSettings
 */
export interface ShippingMethodBaseSettings {
    /**
     * Flat rate per order. 
     * @type {number}
     * @memberof ShippingMethodBaseSettings
     */
    rate?: number;
}

export function ShippingMethodBaseSettingsFromJSON(json: any): ShippingMethodBaseSettings {
    return ShippingMethodBaseSettingsFromJSONTyped(json, false);
}

export function ShippingMethodBaseSettingsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ShippingMethodBaseSettings {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'rate': !exists(json, 'rate') ? undefined : json['rate'],
    };
}

export function ShippingMethodBaseSettingsToJSON(value?: ShippingMethodBaseSettings | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'rate': value.rate,
    };
}


